version: '3'
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.221.0/28

services:
  nginx:
    image: library/nginx:1.19.2-alpine
    restart: on-failure
    depends_on:
      - php-fpm
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/app:ro
    networks:
      - internal

  mysql:
    image: library/mariadb:10.5.5
    restart: on-failure
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - internal

  php-fpm:
    build:
      context: ./docker/php-fpm
    restart: on-failure
    depends_on:
      - mysql
    user: ${UID}:${GID}
    working_dir: /app
    environment:
      COMPOSER_HOME: /tmp
      XDEBUG_CONFIG: "remote_host=192.168.221.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
      APP_ENV: ${APP_ENV}
    volumes:
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php-fpm/php-cli.ini:/usr/local/etc/php/php-cli.ini:ro
      - ./app:/app
    networks:
      - internal